### ISSUE TITLE
Broker/brokerless

### ISSUE THREAD

**Issue by WattsC-90** [tommasobertoni/Iris.NET#4]
Hi, is it possible to run this package as a brokerless system? The example shows creating a service on a node, but it would be great if it could have a service on all nodes.. Or something similar.
Thanks

**Comment by tommasobertoni** [comment]
Hi, you don't have any limit about the number of channels subscriptions you can have on a node. `IrisClientNode`s use a single socket to connect to the server, and that's the entry point to the pubsub network.

I'm not sure I understood your question, though: what do you mean with "_a service on all nodes_"?
Can you provide some code example of what you would like to achieve? thanks

**Comment by WattsC-90** [comment]
A code example would be quite difficult.. See the alljoyn architecture [0] for what i am trying to find, where there are multiple "servers" on the network, so if one "server" goes down, the messaging doesnt stop.. A brokerless system.
[0]  https://allseenalliance.org/framework/documentation/learn/architecture

**Comment by tommasobertoni** [comment]
Oh, I get it now. You would like a distributed routing system, am I right?
Well, at the moment the library doesn't support that, because it relies on the existence of a single `IrisServer`.
Is this what you meant?

**Comment by WattsC-90** [comment]
Exactly right! Sorry, trying to match terminology seems to be the more difficult bit!;) 
Thanks for the information and taking the time to figure out what i meant!!

**Comment by tommasobertoni** [comment]
Anyway, that's an interesting concept and I will look into that. If the feature gets rated doable, I'll let you know.

**Comment by WattsC-90** [comment]
Thanks! 
Id like to use the alljoyn framework but unfortunately it doesnt have a pure .net port anymore, only wrappers.. And im not entirely keen on that!

**Comment by tommasobertoni** [comment]
Well, potentially: would you be interested in helping to develop the feature?

**Comment by WattsC-90** [comment]
I will have a look through the code during the week and let you know? Dont want to commit to anything before iv investigated first!

**Comment by tommasobertoni** [comment]
Completely agree. In the meantime that you read the code, I'll think about the architecture and what would change.
We'll be in touch and we will discuss about the feasibility of the feature in the next weeks. Alright?

**Comment by WattsC-90** [comment]
Sure, sounds like a plan!

**Comment by tommasobertoni** [comment]
Hey @WattsC-90, have you had some time to look at the code? What are your thoughts about the implementation?
